#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch

from transport_attention_fv.data import generate_split
from transport_attention_fv.utils import load_yaml, resolve_path, runtime_manifest, save_json, sha256_file


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    config = load_yaml(args.config)
    problem = config["problem"]
    root = resolve_path(args.config, config["data"]["directory"]) / problem
    root.mkdir(parents=True, exist_ok=True)
    device = torch.device(args.device)
    seeds = config["data"]["split_seeds"]
    manifest_path = root / "manifest.json"
    existing_splits = [root / f"{split}.pt" for split in ("train", "validation", "test")]
    if any(path.exists() for path in existing_splits) and not args.force:
        if not manifest_path.exists():
            raise RuntimeError(
                f"Existing data have no protocol manifest: {root}. Move the directory aside or rerun with --force."
            )
        prior = json.loads(manifest_path.read_text(encoding="utf-8"))
        if prior.get("data_config") != config["data"]:
            raise RuntimeError(
                f"Existing data were generated by a different protocol: {root}. "
                "Do not mix them; move the directory aside before regenerating."
            )
    for split in ("train", "validation", "test"):
        path = root / f"{split}.pt"
        if path.exists() and not args.force:
            print(f"skip existing {path}", flush=True)
            continue
        split_config = dict(config["data"])
        split_factor_key = f"reference_factor_{split}"
        if split_factor_key in split_config:
            split_config["reference_factor"] = int(split_config[split_factor_key])
        generate_split(
            problem, split_config, int(config["data"][f"{split}_samples"]),
            int(seeds[split]), path, device,
        )
    save_json(root / "generation_runtime.json", runtime_manifest())
    save_json(root / "manifest.json", {
        "problem": problem,
        "config": str(args.config.resolve()),
        "data_config": config["data"],
        "splits": {
            split: {
                "samples": int(config["data"][f"{split}_samples"]),
                "seed": int(seeds[split]),
                "sha256": sha256_file(root / f"{split}.pt"),
            }
            for split in ("train", "validation", "test")
        },
    })


if __name__ == "__main__":
    main()
